### ISSUE TITLE
oci runtime error

### ISSUE THREAD

**Issue by niget2002** [tiangolo/uvicorn-gunicorn-fastapi-docker#1]
Using the documentation in the README, getting the following error:

> docker run --name testwebapp -p 80:80 testwebapp
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exec format error".

**Comment by poolebu** [comment]
I just tried out the readme, on a windows docker with ubuntu wsl setup, and it works very, very good. I hope this helps somehow.

**Comment by tiangolo** [comment]
Thanks @poolebu for reporting it :smile:
