### ISSUE TITLE
python 3.10 image

### ISSUE THREAD

**Issue by emil45** [tiangolo/uvicorn-gunicorn-fastapi-docker#129]
Hello,

Not sure if there is another issue open.
Can we expect an image for python 3.10 soon?

Thanks

**Comment by justurbo** [comment]
@tiangolo Any news on the 3.10 Docker image? We want to pattern match!

**Comment by padauer** [comment]
@tiangolo any timeline on this? we would really appreciate a 3.10 image :)

**Comment by AlTosterino** [comment]
@tiangolo Bump ;)

**Comment by AlTosterino** [comment]
FYI: https://github.com/tiangolo/uvicorn-gunicorn-docker/pull/99

**Comment by SionAbes** [comment]
bump too.. We could really do with using the case-switch statements. Though this is probably a good excuse to go and build our own container now.

**Comment by nanonybit** [comment]
bump as well !!!
we could really use the switch case statements 
Thanks

**Comment by kozaczinioo** [comment]
bump. It would really speed up my work.

**Comment by arnonmoscona** [comment]
Bump too. Would save work and would improve maintainability

**Comment by kostaskonkk** [comment]
Bump! I am checking it everyday

**Comment by azhard4int** [comment]
Just bumping this.

**Comment by Kastakin** [comment]
Bumping, 3.10 and its switch case are really important!

**Comment by Charlie-iProov** [comment]
bump!

**Comment by nameer** [comment]
Any update on this?

**Comment by tiangolo** [comment]
Hey all! Thanks for the discussion here! I added Python 3.10 and 3.11 last Friday. :tada: 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Comment by justurbo** [comment]
@tiangolo Thanks Sebastián! Really appreciate what you’ve done. We really love FastAPI at our [high traffic](https://howmanyfps.com) and [renewable energy](https://nash-apps.com) projects.

**Comment by tiangolo** [comment]
That's so cool! Thanks for sharing @justurbo 🚀
