### ISSUE TITLE
How to install additional python modules?

### ISSUE THREAD

**Issue by lucamanga** [tiangolo/uvicorn-gunicorn-fastapi-docker#14]
Hello, I have a doubt: how to install additional python modules, like those that supports postgres or unixodbc connections?

**Comment by srose4** [comment]
Would someone give some help on this issue?  I am also having a hard time getting pyodbc installed into my docker image.  Thanks

**Comment by nhjeon** [comment]
I had same problem and below are two ways I solved it.

**1. Using pip**
Create 'requirements.txt' in app folder.
Create 'prestart.sh' in same folder(https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/#custom-appprestartsh)
`pip install -r requirements.txt`

or

Edit the docker file as below.
`FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
COPY ./app /app
WORKDIR /app
RUN pip install -r requirements.txt`

**2. Install additional package in local.**
` pip install sqlalchemy -t ./app `
`FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
COPY ./app /app`

**Comment by Sefiris** [comment]
If you have followed [Deployment](https://fastapi.tiangolo.com/deployment/) and written a bigger application like in [Bigger Applications with Multiple Files](https://fastapi.tiangolo.com/tutorial/bigger-applications/) then you can use the following Dockerfile to install your pip dependencies.

```
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

COPY ./app /app/app
COPY requirements.txt /
RUN pip install --no-cache-dir -U pip
RUN pip install --no-cache-dir -r /requirements.txt
```

assumes you have a requirement.txt created from a `pip freeze > requirements.txt`

**Comment by tiangolo** [comment]
Thanks for the help here everyone!

Yeah, I think you got it. If you want to use the Docker cache you could also add the requirements in `RUN` directives like:

```Dockerfile
RUN pip install psycopg2-binary
```

Or something equivalent to the `requirements.txt` file if you use Poetry or other tool.
