### ISSUE TITLE
Adding gunicorn_conf.py removes all default gunicorn configs

### ISSUE THREAD

**Issue by weiyiyin0321** [tiangolo/uvicorn-gunicorn-fastapi-docker#16]
When I create a gunicorn_conf.py to increase timeout time, I think it is removing all configurations from the default configs in the docker image. Is there a way to keep all the other configs set by the default config file (ex. # of works, host, port)? 

Right now I'm just copying the default config file and adding the additional timeout variable.

Also FYI for anyone looking for the default gunicorn_conf.py, it is [here](https://github.com/tiangolo/uvicorn-gunicorn-docker/tree/master/python3.7).

**Comment by tiangolo** [comment]
Yeap, that would be the way to do it. It's also the simplest, clearest, and most explicit.
