### ISSUE TITLE
set --preload 

### ISSUE THREAD

**Issue by SaschaHeyer** [tiangolo/uvicorn-gunicorn-fastapi-docker#185]
Hi 
what would the ML community do without you. 
So many great ML models all deployed with FastAPI

How can I easily set --preload with uvicorn-gunicorn-fastapi-docker? Any elegant way? 

```
if __name__ == "__main__":
    uvicorn.run(app, debug=True, port=8080)
```

Thanks

**Comment by jda5** [comment]
Could you expand on this a little bit more? 

My first instinct is to define it in the `docker-compose.yml` file but I am not sure if that is what you are asking.

**Comment by tiangolo** [comment]
Hey there! Thanks! I'm glad the tools are useful!

First, you might actually not need this image: https://fastapi.tiangolo.com/deployment/docker/

Next, could you elaborate your question? Maybe with a full example and a description of your problem or what you're trying to solve.
