### ISSUE TITLE
Pull access denied for ttiangolo/uvicorn-gunicorn-fastapi

### ISSUE THREAD

**Issue by PyDataBlog** [tiangolo/uvicorn-gunicorn-fastapi-docker#20]
H, I get this error when I try to build an image from this tool: 

`pull access denied for ttiangolo/uvicorn-gunicorn-fastapi, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

How can I get past this? It doesn't happen with other repos.

**Comment by PunkDork21** [comment]
Might be because of the extra `t` you have in `tiangolo/uvicorn-gunicorn-fastapi`?

**Comment by PyDataBlog** [comment]
That solved it.

**Comment by tiangolo** [comment]
Thanks for the help here @PunkDork21 ! :clap: :bow: 

Thanks for reporting back and closing the issue @PyDataBlog  :+1:
