### ISSUE TITLE
GUNICORN_CONF set, file exists, but it's not being read

### ISSUE THREAD

**Issue by niloct** [tiangolo/uvicorn-gunicorn-fastapi-docker#22]
Hi all,

My current issue: I can't seem to make gunicorn/uvicorn honor the `gunicorn_conf.py` file I write at the /app folder, and all errors/access logs are being output into stdout.

Could you please advise the best way to make `errorlog` and `accesslog` directives work ? For now I just want to output those to a file.

My `gunicorn_conf.py`:

```
import json
import multiprocessing
import os

workers_per_core_str = os.getenv("WORKERS_PER_CORE", "1")
web_concurrency_str = os.getenv("WEB_CONCURRENCY", None)
host = os.getenv("HOST", "0.0.0.0")
port = os.getenv("PORT", "80")
bind_env = os.getenv("BIND", None)
use_loglevel = os.getenv("LOG_LEVEL", "info")
if bind_env:
    use_bind = bind_env
else:
    use_bind = "%s:%s" % (host, port)

cores = multiprocessing.cpu_count()
workers_per_core = float(workers_per_core_str)
default_web_concurrency = workers_per_core * cores
if web_concurrency_str:
    web_concurrency = int(web_concurrency_str)
    assert web_concurrency > 0
else:
    web_concurrency = max(int(default_web_concurrency), 2)

# Gunicorn config variables
loglevel = use_loglevel
workers = web_concurrency
bind = use_bind
keepalive = 120

########### This is not being observed #######
errorlog = "/app/log/gunicorn.log"
accesslog = "/app/log/gunicorn.access.log"
capture_output = True
########### /This is not being observed #######

# For debugging and testing
log_data = {
     "loglevel": loglevel,
     "workers": workers,
     "bind": bind,
     # Additional, non-gunicorn variables
     "workers_per_core": workers_per_core,
     "host": host,
     "port": port,
}
print(json.dumps(log_data))
```

Seems like the file is not being observed at all, even though I've put the `GUNICORN_CONF` environment variable on my docker compose file.

Any clues ?

Thanks for your attention.

**Comment by niloct** [comment]
I've managed to find the source of the problem.

I was using `start-reload.sh` on my `docker-compose.yml`, (i.e. `command: ['/start-reload.sh']`) which doesn't fire gunicorn, instead it fires uvicorn and doesn't pass the configuration file as a parameter.

**Comment by huanggengkeng** [comment]
@niloct how do you to solve it

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue @niloct  :+1:
