### ISSUE TITLE
Server shutting down in production

### ISSUE THREAD

**Issue by kinoute** [tiangolo/uvicorn-gunicorn-fastapi-docker#23]
Hey there,

I saw the other issue #8 that seems similar to my problem but the solution described there doesn't fix my problem.

I have a basic FastAPI Docker API with one endpoint (no async) that returns a prediction for a machine learning model. Everything works great when running with `/start_reload.sh`.

But as soon as I remove it (and, I think, use Gunicorn instead of unicorn), as soon as I curl the endpoint to get a prediction, I get:

> 2019-12-20T15:32:03.282698361Z INFO:root:New prediction asked!
2019-12-20T15:32:03.283512479Z INFO:root:Converting JSON data to plain email...
2019-12-20T15:32:03.354365024Z INFO:root:Getting predictions for mail #176161..
2019-12-20T15:32:03.363742952Z {"loglevel": "info", "workers": 4, "bind": "0.0.0.0:80", "workers_per_core": 1.0, "host": "0.0.0.0", "port": "80"}
2019-12-20T15:32:03.363773295Z Converting to features started.
100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
2019-12-20T15:32:03.889738388Z [2019-12-20 15:32:03 +0000] [9] [INFO] Shutting down
2019-12-20T15:32:03.990590055Z [2019-12-20 15:32:03 +0000] [9] [INFO] Waiting for connections to close. (CTRL+C to force quit)

After a while, I guess the Gunicorn `timeout`, the server restarts. This is really happening when asking the model to return a prediction. For example, I made sure in my code that if my json data is bad, I return a HTTPException before reaching the model for prediction. And if I test that, it works. I don't get the "shutting down" message.

Could it be related to the concurrency/parallelism stuff? I tried to edit the Gunicorn conf, added a timeout etc, nothing works except unicorn with `/start-reload.sh`. But `/start-reload.sh` adds a lot of CPU use (around 50% in my case instead of 1%) therefore I can't use that in production.

Is there a way to use Gunicorn but disable all the fancy stuff that could cause this issue?

Thank you!

**Comment by tiangolo** [comment]
It's probably that Gunicorn is killing your worker while the worker is taking some time to do its thing. You can now set the timeout for killing workers: https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker#graceful_timeout :rocket:

**Comment by BruBel** [comment]
I'm facing the same issue
`INFO:     Started server process [1]                                                                                                                                                                               INFO:     Waiting for application startup.                                                                                                                                                                         INFO:     Application startup complete.                                                                                                                                                                            INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)                                                                                                                                            INFO:     192.168.99.1:65102 - "GET /docs HTTP/1.1" 200 OK                                                                                                                                                         INFO:     192.168.99.1:65102 - "GET /openapi.json HTTP/1.1" 200 OK                                                                                                                                                 Processando categorias - Layer 1                                                                                                                                                                                   0                                                                                                                                                                                                                  100%|██████████| 1/1 [00:00<00:00,  5.14it/s]                                                                                                                                                                      INFO:     Shutting down                                                                                                                                                                                            INFO:     Waiting for connections to close. (CTRL+C to force quit)`

After call prediction function from simpletransformers BERT model, my api get shut down. I've already tried to increase TIMEOUT_LIMIT, graceful_timeout, KEEP_ALIVE, but nothing worked. Another sugestion?
