### ISSUE TITLE
Pin versions?

### ISSUE THREAD

**Issue by slhck** [tiangolo/uvicorn-gunicorn-fastapi-docker#24]
Would it make sense to pin the version of at least FastAPI (potentially the Uvicorn and Gunicorn as well) such that the images create reproducible builds?

I've ran into this often, where I define a specific version of this image (e.g. `python3.7-2019-12-11`), but whenever I build it, it just pulls the latest version of FastAPI, whatever that is at the time of building (due to `RUN pip install fastapi`). This may lead to inconsistencies between local versions (which I can specify in `requirements.txt`) and Docker builds.

**Comment by tiangolo** [comment]
You could pin the `fastapi` version in your own `Dockerfile` or you could remove the `pip install fastapi` and instead use your own `requirements.txt` file.
