### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by heitorPB** [tiangolo/uvicorn-gunicorn-fastapi-docker#26]
I have the following Dockerfile:

```
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

COPY . /app
#COPY ./requirements.txt /app
#
#run pip install --upgrade pip && \
#    pip install -r /app/requirements.txt

ENV APP_NAME "control.controller:app"
```
I have a folder  `control` and a `controller.py` in it.

But my control app is not started. It starts the simple `main.py` from this repo instead.

Any ideas?

**Comment by tianxiewuhua** [comment]
```docker run -d -p 80:80 -e MODULE_NAME="custom_app.custom_main" myimage```

you should set the MODULE_NAME

**Comment by tiangolo** [comment]
Thanks for the help @tianxiewuhua ! :cake: 

@heitorPB does that solve your problem? May we close this issue?

**Comment by heitorPB** [comment]
that solved my problem, thanks @tianxiewuhua and @tiangolo !
