### ISSUE TITLE
Debug mode?

### ISSUE THREAD

**Issue by wshayes** [tiangolo/uvicorn-gunicorn-fastapi-docker#3]
Trying to figure out how to turn on auto-reloading (e.g. debug mode) while using docker. I develop in the docker container by volume mounting the app directory into the docker container so any changes I make to the code are available immediately inside the running docker container. I can't figure out how to start debug mode using gunicorn with uvicorn.

Any ideas?

PS Great project and thanks!

**Comment by rudmac** [comment]
just create a env GUNICORN_CMD_ARGS="--reload"

**Comment by wshayes** [comment]
Aarrgghhh!  Yes that works great - read somewhere that didn’t work and didn’t test it. Shame on me.

Thanks!  

Thanks also for the env tip - works great with Docker compose.

**Comment by tiangolo** [comment]
@wshayes 

> Great project and thanks!

Awesome! I'm glad it's working for you.

@rudmac Thanks for your help here! It's very appreciated. :clap: :taco: 

---

There's a new integrated script `/start-reload.sh` specifically for this.

It runs only Uvicorn with `--reload`, optimal for development.

Check the updated docs here: https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker#development-live-reload

**Comment by wshayes** [comment]
Thanks - I'll update the writeup I made for it: https://medium.com/@williamhayes/fastapi-starlette-debug-vs-prod-5f7561db3a59  (future note for myself (ever searched for a solution to a problem and find an old post with the answer - still undecided if it is embarrassing or an example of impressive forethought))

FYI - looks like --reload and --debug are equivalent currently in uvicorn. I'll make a note of that as well.

**Comment by tiangolo** [comment]
Thanks! And great post!

In Uvicorn, `--debug` was the "standard" up to `0.5.0`, now it will be `--reload`, it's very recent.

Check: https://github.com/tiangolo/fastapi/issues/66

**Comment by ermarkar** [comment]
I have tried 

`uvicorn.run(self.app, host=host, port=port, debug=True)`

and this 

`uvicorn.run(self.app, host=host, port=port, reload=True)`

not working in VSCode

**Comment by mironnn** [comment]
Can reloading be working without a gunicorn?

**Comment by wshayes** [comment]
> Can reloading be working without a gunicorn?

Not easily without either `uvicorn` or `gunicorn`. It's possible to replicate reload without it, but you still need an ASGI server to run FastAPI anyway.
