### ISSUE TITLE
FastAPI on Alpine - smaller stack size?

### ISSUE THREAD

**Issue by matanos5** [tiangolo/uvicorn-gunicorn-fastapi-docker#31]
Hi - Great project! I love FastAPI. Thanks for maintaining it!

I read this article:
https://pythonspeed.com/articles/alpine-docker-python/

Was wondering - can FastAPI face a bottleneck due to Alpine's smaller stack size?

Would love to know what you think about what's written in that article.

Thanks!

**Comment by tiangolo** [comment]
I always prefer to use the standard default Debian images, but as many users really like Alpine for some reason, I have those images too. But I normally use the default ones with Debian.

**Comment by matanos5** [comment]
@tiangolo Great, got my question answered, closing.

Thanks :)
