### ISSUE TITLE
Adding a new APK package to the image

### ISSUE THREAD

**Issue by AntonAleksandrov13** [tiangolo/uvicorn-gunicorn-fastapi-docker#51]
As the your image is based on Alpine, I need to install additional system dependencies such as cron. However, apk cannot be found while running a Docker build.

Is there a workaround for that?

**Comment by AntonAleksandrov13** [comment]
Nvm, I have used the wrong image and turns out that I have access to package manager

**Comment by tiangolo** [comment]
Cool, thanks for reporting back. I'm then gonna close this issue. :heavy_check_mark:
