### ISSUE TITLE
Document request: How to deploy to DigitalOcean

### ISSUE THREAD

**Issue by shinokada** [tiangolo/uvicorn-gunicorn-fastapi-docker#58]
It will be great if you can add a doc about how to deploy the image to a hosting service such as DigitalOcean. 
Covering the security issues and step by step tutorial will be very practical for many.

**Comment by jgannondo** [comment]
@shinokada we're working on a beta that might be helpful ... email me on jgannon@do.co and I can share more. Thanks!

**Comment by tiangolo** [comment]
I imagine you solved the problem, thanks for coming back to close the issue @shinokada! ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
