### ISSUE TITLE
add python 3.9 tag

### ISSUE THREAD

**Issue by CircleOnCircles** [tiangolo/uvicorn-gunicorn-fastapi-docker#61]
add python 3.9 tag since it is released.

**Comment by rednafi** [comment]
Yes, please. I'd like to test out my apps on python3.9.

**Comment by kamikaze** [comment]
Please

**Comment by hopenbr** [comment]
I had issues getting 3.9 to work my FastAPI service, 

Using a `python:3.9-slim` base image I needed to install a few more dependencies than before with fastapi 3.8-slim version (FastAPI 0.55.1)

```dockerfile
...
RUN apt-get update && apt-get install -y build-essential=12.6 \ 
&& pip install --no-cache-dir uvloop==0.14.0 httptools==0.1.1 uvicorn==0.13.0 gunicorn==20.0.4 fastapi==0.62.0 \
...
```

I needed to install `build-essential`, `uvloop` and `httptools`, without these FastAPI api would not startup. 
Not sure why, yet this did the trick for me

**Comment by MROS** [comment]
Please

**Comment by gl3nn** [comment]
@tiangolo Are there any blockers for 3.9?

**Comment by WinnerOK** [comment]
I have built `uvicorn-gunicorn-fastapi` images for `python3.9` based on [these](https://github.com/WinnerOK/uvicorn-gunicorn-docker) images.  

Feel free to use the images until @tiangolo merge either [#64](https://github.com/tiangolo/uvicorn-gunicorn-docker/pull/64) or [#52](https://github.com/tiangolo/uvicorn-gunicorn-docker/pull/52) at [uvicorn-gunicorn-docker repository](https://github.com/tiangolo/uvicorn-gunicorn-docker).

DockerHub links and sources are available in my [repo](https://github.com/WinnerOK/uvicorn-gunicorn-fastapi-docker).

Current images are based on PR #67.

**Comment by czyzby** [comment]
@tiangolo Any updates on this?

**Comment by anton-petrov** [comment]
Also share my fork with updated versions of python 3.9 and alpine 3.13 there ^_^

docker hub: https://hub.docker.com/repository/docker/antonapetrov/uvicorn-gunicorn
github repo: https://github.com/anton-petrov/uvicorn-gunicorn-docker

**Comment by christian-semalytix** [comment]
So, are we skipping Python 3.9 and jumping straight to 3.10 then?

**Comment by lanasalameh1** [comment]
Hi
any updates on this? when do you expect the official release for this?

**Comment by tiangolo** [comment]
Thanks everyone for the discussion and interest! And thanks @graue70 for the PR! It is now available. :tada:
