### ISSUE TITLE
fastapi build docker and publishto k8s,do i need gunicorn+fastapi or not ??

### ISSUE THREAD

**Issue by stringk245** [tiangolo/uvicorn-gunicorn-fastapi-docker#64]
Uvicorn
Uvicorn is a lightning-fast "ASGI" server.

It runs asynchronous Python web code in a single process.

Gunicorn
You can use Gunicorn to manage Uvicorn and run multiple of these concurrent processes.

That way, you get the best of concurrency and parallelism.

#Question

fastapi build docker and publishto k8s, so do i need gunicorn+fastapi or not ?? , just uvicorn+fastapi ?
because k8s can create multiple Pods to implementation these concurrent processes  Instead of Gunicorn

Can I release directly to the production environment with uvicorn+fastapi （no gunicorn and build docker to k8s）??

gunicorn+fastapi -w 1 pk uvicorn+fastapi(no gunicorn manage ), Which performance is higher ??

**Comment by clmno** [comment]
An answer to this question was given on FastAPI repo tiangolo/fastapi#2227

(Just for context.)

**Comment by stringk245** [comment]
> An answer to this question was given on FastAPI repo [tiangolo/fastapi#2227](https://github.com/tiangolo/fastapi/issues/2227)
> 
> (Just for context.)

Thank you very much！！ again

**Comment by tiangolo** [comment]
Thanks for the help @clmnin ! 🍰 

And thanks for closing the issue @stringk245 ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
