### ISSUE TITLE
infinite [INFO] Booting worker with pid: 461 while deploying to heroku via docker image

### ISSUE THREAD

**Issue by rvigneshw** [tiangolo/uvicorn-gunicorn-fastapi-docker#68]
My Dockerfile

FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
COPY ./app /app

**Comment by manojlds** [comment]
Seeing this even on building and running the image on local

**Comment by manojlds** [comment]
Check this - https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/issues/42

**Comment by tiangolo** [comment]
Hey there, I'm not using Heroku, I'm not sure about their internals. If you still have issues, you could try first running it locally and seeing if it works correctly. If it does, then the problem is probably on the Heroku side (configs, etc).

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
