### ISSUE TITLE
Is there a tiangolo/uvicorn-gunicorn-fastapi:python3.7-slim image?

### ISSUE THREAD

**Issue by ohmeow** [tiangolo/uvicorn-gunicorn-fastapi-docker#71]
I noticed there is one of the uvicorn-gunicorn image ... but I love the + fastapi images because it includes the reload.sh file.

Thanks

**Comment by tiangolo** [comment]
There are slim versions for Python 3.8 and 3.9 🎉 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
