### ISSUE TITLE
When usnig ENTRYPOINT command container exited with code 0

### ISSUE THREAD

**Issue by PetrShchukin** [tiangolo/uvicorn-gunicorn-fastapi-docker#77]
I add ENTRYPOINT["entrypoint.sh"] in Dockerfile, and created a custom script entrypoint.sh. Whenever I start the container I got message exited with code 0.
P.S. I've tested with an empty script and got the same issue

**Comment by tiangolo** [comment]
You are not supposed to create a custom `ENTRYPOINT`, the main point in this image is the entrypoint it provides, if you create a custom one, you are no longer using what the image provides.

If you need to customize things, it's probably better in a different way. For example: https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker#custom-appprestartsh

Also, have in mind that you most probably don't need this Docker image: https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker#-warning-you-probably-dont-need-this-docker-image

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
