### ISSUE TITLE
What is maximum query string length?

### ISSUE THREAD

**Issue by shizidushu** [tiangolo/uvicorn-gunicorn-fastapi-docker#78]
When I send the request with very long query string (A list of string). I get WARNING: Invalid HTTP request received.

After searched, I guess the cause may be there is limit on the query string length. 

So, what is the maximum query string length? Can I change it?

**Comment by shizidushu** [comment]
Just find it is an upstream issue https://github.com/MagicStack/httptools/issues/43

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
