### ISSUE TITLE
Unicorn reload not working

### ISSUE THREAD

**Issue by samgj18** [tiangolo/uvicorn-gunicorn-fastapi-docker#79]
When I try to run this command `sudo docker run --name test -d -p 8000:8000 -v $(pwd):/app myimage /start-reload.sh` (I changed the ports). The reload feature is not working, all I get is:

`error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/app/venv/bin/python'`

**Comment by csutera** [comment]
@samgj18 did you find a solution for this issue? I am experiencing the same with the `start.sh` and the `start-reload.sh`.

**Comment by samgj18** [comment]
Hey @csutera unfortunately this was the last time I touched Python 🥲
