### ISSUE TITLE
Python 3.9 version

### ISSUE THREAD

**Issue by SNavgale** [tiangolo/uvicorn-gunicorn-fastapi-docker#80]
Hi,

Is there a plan to get Python 3.9 version support?

**Comment by confiq** [comment]
sure #67

**Comment by SNavgale** [comment]
Thanks

**Comment by tiangolo** [comment]
Thanks for the help here @confiq ! 👏  🙇 

Thanks for reporting back and closing the issue @SNavgale  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
