### ISSUE TITLE
Getting it to work with HTTPS?

### ISSUE THREAD

**Issue by vinhta916** [tiangolo/uvicorn-gunicorn-fastapi-docker#82]
How do I get this working with HTTPS?

**Comment by tiangolo** [comment]
Probably with a frontend TLS termination proxy like Traefik.

I assume you solved it, thanks for closing the issue 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
