### ISSUE TITLE
Setting the content length limit

### ISSUE THREAD

**Issue by ArneKlein** [tiangolo/uvicorn-gunicorn-fastapi-docker#88]
Hi, sorry if this is a stupid question, however, we need to increase the content size limit for file uploads.
Can we just replace the nginx config or are you doing anything special in there?

Or is there an even better way?

**Comment by ArneKlein** [comment]
My bad, I had an routing issue, which led to swagger having the wrong URL in the background and calling another container with nginx. Which now explains why I couldn't get it to work nor could find the nginx.conf file.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
